# -*- coding: utf-8 -*-
"""
Created on Wed Mar 10 19:25:49 2021

@author: Roger

Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed
four million, find the sum of the even-valued terms.
"""

n1 = 1
n2 = 2
n3 = 0
fibSeq = [1, 2]
fsum = 0

while n3 <= 4000000:
    n3 = n1 + n2
    if n3 <= 4000000:
        fibSeq.append(n3)
        n1 = n2
        n2 = n3

for x in range(0, len(fibSeq)):
    if fibSeq[x] % 2 == 0:
        fsum += fibSeq[x]

print(fibSeq)
print(fsum)

""" Result:
    fsum = 4613732
    fibSeq = [1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597,
              2584, 4181, 6765, 10946, 17711, 28657, 46368, 75025, 121393,
              196418, 317811, 514229, 832040, 1346269, 2178309, 3524578] """
